"""accel_dse: analytical NPU + SRAM + HBM/LPDDR multi-domain inference DSE.

Domains: LLM (GQA/MoE/MLA) + video (DiT-like) + protein (encoder + optional pair).
Inference-only, fixed-dataflow NPU (not GPGPU). No fake PDK power/area
(v0.25 energy/cost = user-knob ASSUMED stub only: tdp_w / watts_per_tops / cost_per_card_usd).
Single-card first; multi-card TP/PP/EP + C2C + IB/RoCE KV fabric (LLM + video/protein; assumed BW).
MetricsCard scale_efficiency/speedup vs chips=1 baseline (v0.25).
v0.26 opt-in assumed non_gemm_overhead + dtype_mac_factors (default off / 1.0).
All absolute hardware numbers are *assumed/uncalibrated* unless derived from
shape + tiling + capacities.
"""

__version__ = "0.31.1"

from .model_shape import ModelShape, TOY_SHAPE, ILLUSTRATIVE_27B, ILLUSTRATIVE_MOE, ILLUSTRATIVE_MLA
from .npu import NPUConfig, gemm_cycles, gemm_utilization
from .memory import (
    SRAMConfig,
    SRAMPartitions,
    ExternalMemory,
    HBM_PRESET,
    LPDDR_PRESET,
    derive_sram_partitions,
    SramPolicy,
)
from .sku import SKU_100T, SKU_1P, SKU_BASELINE, SKUPreset, get_sku
from .dtype import (
    DTypePreset,
    DTYPE_FP16,
    DTYPE_FP8,
    DTYPE_INT8,
    DTYPE_INT4,
    QuantPreset,
    get_dtype,
    get_quant,
)
from .evaluate import EvalConfig, evaluate_inference
from .scan import (
    run_default_scan,
    run_sku_scan,
    run_dtype_sweep,
    run_ctx_sweep,
    run_sram_sweep,
    run_quant_sweep,
    run_batch_sweep,
    run_moe_sweep,
    run_mla_sweep,
    run_tp_sweep,
    run_scaleup_scan,
    run_kv_fabric_sweep,
    run_parallel_sweep,
    run_pp_sweep,
    export_csv_bundle,
    run_video_sweep,
    run_protein_sweep,
    export_video_protein_csv,
    run_compare_domains,
    export_compare_domains_csv,
)
from .workloads import (
    VideoShape,
    ProteinShape,
    ILLUSTRATIVE_DIT_VIDEO,
    ILLUSTRATIVE_LARGE_DIT,
    ILLUSTRATIVE_PROTEIN_PAIR,
    TOY_VIDEO,
    TOY_PROTEIN,
    evaluate_video,
    evaluate_protein,
    list_shapes,
)

from .workbench import (
    WorkbenchConfig,
    MetricsCard,
    ParallelOverride,
    CalibrationOverrides,
    evaluate_workbench,
    workbench_scan,
    workbench_parallel_matrix,
    workbench_mem_sweep,
    format_scan_table,
    format_parallel_table,
    format_mem_sweep_table,
    export_scan_csv,
    export_metrics_card_json,
    export_metrics_card_md,
    enumerate_parallel_combos,
)
from .catalog import catalog_counts, load_catalog_raw
from .series import (
    SeriesEntry,
    SERIES_REGISTRY,
    PRODUCT_SERIES_IDS,
    get_series,
    list_series,
    resolve_llm_shape,
    resolve_video_shape,
    resolve_protein_shape,
)
from .memory import MemGeometry, memory_from_geometry, peak_bandwidth_GBps_from_geometry
from .npu import npu_from_cores, cores_from_npu, npu_from_pe

from .package_ranges import (
    PackageOption,
    ComputeOption,
    PACKAGE_CATALOG,
    COMPUTE_CATALOG,
    get_package,
    get_compute,
    list_packages,
    list_compute,
    list_compute_primaries,
    format_package_table,
    format_compute_table,
    package_counts,
    CORE_TOPS_GRID,
    CLUSTER_TOPS_GRID,
)
from .mem_catalog import (
    MemSpec,
    make_spec,
    parse_mem_id,
    sweep_specs,
    catalog_dict as memory_catalog_dict,
    TAG_ORDER as MEM_TAG_ORDER,
    TAG_ZH as MEM_TAG_ZH,
)
from .report import collect_report_data, render_html, write_report

from .scaleup import (
    TPConfig,
    ParallelConfig,
    C2CLink,
    C2C_100,
    C2C_200,
    C2C_400,
    C2C_800,
    KvFabricLink,
    KV_FABRIC_PRESETS,
    evaluate_scaleup,
    evaluate_parallel,
    ring_allreduce_bytes,
    tree_allreduce_bytes,
    moe_alltoall_bytes,
    scale_domain_parallel,
    get_c2c,
    get_kv_fabric,
    kv_card_fraction,
    sync_collectives_per_token,
    DEFAULT_C2C_LATENCY_US,
)

from .econ import EnergyCostKnobs, apply_energy_cost
from .scenarios import ScenarioPreset, evaluate_presets, get_preset, list_presets

__all__ = [
    "MemSpec",
    "make_spec",
    "parse_mem_id",
    "sweep_specs",
    "memory_catalog_dict",
    "MEM_TAG_ORDER",
    "MEM_TAG_ZH",
    "kv_card_fraction",
    "sync_collectives_per_token",
    "DEFAULT_C2C_LATENCY_US",
    "ModelShape",
    "TOY_SHAPE",
    "ILLUSTRATIVE_27B",
    "ILLUSTRATIVE_MOE",
    "ILLUSTRATIVE_MLA",
    "NPUConfig",
    "gemm_cycles",
    "gemm_utilization",
    "SRAMConfig",
    "SRAMPartitions",
    "derive_sram_partitions",
    "SramPolicy",
    "ExternalMemory",
    "HBM_PRESET",
    "LPDDR_PRESET",
    "SKU_100T",
    "SKU_1P",
    "SKU_BASELINE",
    "SKUPreset",
    "get_sku",
    "DTypePreset",
    "DTYPE_FP16",
    "DTYPE_FP8",
    "DTYPE_INT8",
    "DTYPE_INT4",
    "get_dtype",
    "QuantPreset",
    "get_quant",
    "EvalConfig",
    "evaluate_inference",
    "run_default_scan",
    "run_sku_scan",
    "run_dtype_sweep",
    "run_ctx_sweep",
    "run_sram_sweep",
    "run_quant_sweep",
    "run_batch_sweep",
    "run_moe_sweep",
    "run_mla_sweep",
    "export_csv_bundle",
    "run_tp_sweep",
    "run_scaleup_scan",
    "run_kv_fabric_sweep",
    "run_parallel_sweep",
    "run_pp_sweep",
    "TPConfig",
    "ParallelConfig",
    "C2CLink",
    "C2C_100",
    "C2C_200",
    "C2C_400",
    "C2C_800",
    "KvFabricLink",
    "KV_FABRIC_PRESETS",
    "evaluate_scaleup",
    "evaluate_parallel",
    "ring_allreduce_bytes",
    "tree_allreduce_bytes",
    "moe_alltoall_bytes",
    "scale_domain_parallel",
    "get_c2c",
    "get_kv_fabric",
    "VideoShape",
    "ProteinShape",
    "ILLUSTRATIVE_DIT_VIDEO",
    "ILLUSTRATIVE_LARGE_DIT",
    "ILLUSTRATIVE_PROTEIN_PAIR",
    "TOY_VIDEO",
    "TOY_PROTEIN",
    "evaluate_video",
    "evaluate_protein",
    "list_shapes",
    "run_video_sweep",
    "run_protein_sweep",
    "export_video_protein_csv",
    "run_compare_domains",
    "export_compare_domains_csv",
    "WorkbenchConfig",
    "MetricsCard",
    "ParallelOverride",
    "CalibrationOverrides",
    "EnergyCostKnobs",
    "apply_energy_cost",
    "ScenarioPreset",
    "get_preset",
    "list_presets",
    "evaluate_presets",
    "evaluate_workbench",
    "workbench_scan",
    "workbench_parallel_matrix",
    "workbench_mem_sweep",
    "format_scan_table",
    "format_parallel_table",
    "format_mem_sweep_table",
    "export_scan_csv",
    "export_metrics_card_json",
    "export_metrics_card_md",
    "enumerate_parallel_combos",
    "SeriesEntry",
    "SERIES_REGISTRY",
    "PRODUCT_SERIES_IDS",
    "get_series",
    "list_series",
    "resolve_llm_shape",
    "resolve_video_shape",
    "resolve_protein_shape",
    "catalog_counts",
    "load_catalog_raw",
    "MemGeometry",
    "memory_from_geometry",
    "peak_bandwidth_GBps_from_geometry",
    "npu_from_cores",
    "cores_from_npu",
    "npu_from_pe",
    "collect_report_data",
    "render_html",
    "write_report",
    "PackageOption",
    "ComputeOption",
    "PACKAGE_CATALOG",
    "COMPUTE_CATALOG",
    "get_package",
    "get_compute",
    "list_packages",
    "list_compute",
    "list_compute_primaries",
    "format_package_table",
    "format_compute_table",
    "package_counts",
    "CORE_TOPS_GRID",
    "CLUSTER_TOPS_GRID",
]
